Duozin/Models/ErrorViewModel.cs
namespace Duozin.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Duozin/Models/MidModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Duozin.Models
{
    public class MidModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int MartialArts { get; set; }
        public int Fights { get; set; }
        public int Defeats { get; set; }
        public int Victories { get; set; }
        public string Description {get; set;}
    }
}

Duozin/Controllers/DuozinController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Duozin.Repositories.interfaces;
using Duozin.Repositories;
using Duozin.Models;
using Duozin.Data;



namespace Duozin.Controllers
{
    public class DuozinController : Controller
    {
        private readonly IMidRepository _midRepository;
        private readonly IDuozinRepository _duozinRepository;
        

        public DuozinController(IMidRepository midRepository, IDuozinRepository duozinRepository)
        {
            _midRepository = midRepository;
            _duozinRepository = duozinRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Personagens()
        {
            var mids = _midRepository.GetMidList();
            return View(mids);
        }

        public IActionResult List()
        {
            var mids = _midRepository.GetMidList();
            return View(mids);
        }

        [HttpPost]
        public IActionResult StartDuozin(IFormCollection mids)
        {
            List<MidModel> checkedMids = _midRepository.GetMidsId(mids);

            List<MidModel> orderByAgeMids = _duozinRepository.OrderByAge(checkedMids);
            var winner = _duozinRepository.GetWinnerDuozin(orderByAgeMids);

            return View("Winner", winner);
        }


         
        public IActionResult Winner(int id)
        {
            return View();
        }
    }
}

Duozin/Views/Duozin/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="container-fluid">

    <img class="position-absolute top-0 start-50 translate-middle logo" src="./img/logos/logoVertical.png" alt="Logo">


    <a asp-area="" asp-controller="Duozin" asp-action="Personagens">
        <button class="position-absolute top-50 start-50 translate-middle" id="bubblesButton" >

            BORA! 
            <span class="bubbles">
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
                <span class="bubble"></span>
            </span>
        </button>
    </a>



    <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
        <defs>
            <filter id="bubblesReference">
                <feGaussianBlur in="SourceGraphic" stdDeviation="5" result="blur" />
                <feColorMatrix in="blur" type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9"
                    result="highContrastGraphic" />
                <feComposite in="SourceGraphic" in2="highContrastGraphic" operator="atop" />
            </filter>
        </defs>
    </svg>


</div>

Duozin/Views/Duozin/List.cshtml
@model List<MidModel>;
@{
    ViewData["Title"] = "Lista de personagens";
}
<header class="position-absolute top-0 start-50 translate-middle logoList"
    style="background-image: url('../img/logos/logoVertical.png');">
</header>


<button id="backTop" onclick="topFunction()" class="backToTop"><i class='bx bx-chevron-up'></i></button>


<div class="container-md">
    <div class="listMids row">
        @foreach (var mid in Model)
        {
            <div class="rowListMid">
                <div id="@mid.Id" class="contentListMid"
                style="background-image: url('../img/personagens/square/@(mid.Name)Square.webp');">
                    <p>Nome: @mid.Name</p>
                    <p style="margin-top: -15px;" class="idade">Idade: @mid.Age</p>
                    <p style="margin-top: -15px;">Lutas: @mid.Fights</p>
                    <p style="margin-top: -15px;">Vitórias: @mid.Victories</p>
                    <p style="margin-top: -15px;">Derrotas: @mid.Defeats</p>

                    @{
                        string nomeMinusculo = @mid.Name.ToLower().Replace(" ", "-");
                    }

                    <div class="descricao">
                        <a href="https://www.leagueoflegends.com/pt-br/champions/@nomeMinusculo/" target="_blank"><i
                            class='bx bx-right-arrow-alt' title="Clique aqui para ver mais detalhes do personagem"></i></a>

                        <p style="margin-top: -40px; font-size: 20px">Frase de efeito</p>

                        <p style="font-size: 15px;">@mid.Description</p>

                    </div>



                </div>
            </div>
        }
    </div>
</div>


<footer class="footer">
    <h3>Duozin?</h3>
</footer>

Duozin/Views/Duozin/Personagens.cshtml
@model List<MidModel>;
@{
    ViewData["Title"] = "Personagens";
}
<header class="position-absolute top-0 start-50 translate-middle logoHorizontal"
    style="background-image: url('../img/logos/logoHorizontal.png');">
    <div class="headerContent">

        <h3 id="fightersChecked">Selecione 16 Mid laners e inicie</h3>

    </div>
</header>


<div id="notification" class="notification">
    <h3 id="fightersCheckedN">Selecione mais 16 Mid laners</h3>
</div>

<button id="backTop" onclick="topFunction()" class="backToTop"><i class='bx bx-chevron-up'></i></button>

<form method="post" onsubmit="return countCheckbox();" action="@Url.Action("StartDuozin", "Duozin")">
    <div class="startButton">
        <button type="submit" class="start">Iniciar</button>
    </div>
    

    <div class="container-md listFighter">
        @foreach (var mid in Model)
        {
            <div id="@mid.Id" class="cardFighter" onclick="check('@mid.Name'); LutadorSelecionado(@mid.Id) "
            style="background-image: url('../img/personagens/@(mid.Name).png');" data-cardSelect>
                <div class="contentHover">
                    <h4>Lutas</h4>
                    <h4>Vitórias</h4>
                    <h4>Derrotas</h4>
                    <h4>Artes Marciais</h4>
                </div>
                <div class="leftBar">
                    <input style="display: none;" type="checkbox" Id="@mid.Name" name="@mid.Id" />
                    <div>
                        <h4>L</h4>
                        <p>@mid.Fights</p>
                    </div>
                    <div>
                        <h4>V</h4>
                        <p>@mid.Victories</p>
                    </div>
                    <div>
                        <h4>D</h4>
                        <p>@mid.Defeats</p>
                    </div>
                    <div>
                        <h4>AM</h4>
                        <p>@mid.MartialArts</p>
                    </div>
                </div>

                <div class="nomeIdade">
                    <h1>@mid.Name</h1>
                    <span>@mid.Age Anos</span>
                </div>


            </div>
        }
    </div>
</form>

<footer class="footer">
    <h3>Duozin?</h3>
</footer>

Duozin/Views/Duozin/Winner.cshtml
@model MidModel;
@{
    ViewData["Title"] = "Campeão";
}

<div>
    <img style="filter: brightness(15%); background-image: url('../img/personagens/@(Model.Name)w.jpg'); "
        class="imgWinner">
    <span class="position-absolute  start-50 translate-middle logoVictory"
        style="background-image: url('../img/logos/victory.png');">
        <div class="headerContent-Winner">
            <div onClick='window.location="#suporte"'class="hextech-button">Visualizar vencedor</div>
        </div>

        @{
            string nomeMinusculo = @Model.Name.ToLower().Replace(" ", "-");
        }

        <div class="contentWinner position-absolute start-50 translate-middle">
            <div class="imgCircleWinner"
                style="background-image: url('../img/personagens/square/@(Model.Name)Square.webp');">
                <a href="https://www.leagueoflegends.com/pt-br/champions/@nomeMinusculo/" target="_blank"><i
                            class='bx bx-right-arrow-alt' title="Clique aqui para ver mais detalhes do personagem"></i></a>
            </div>

            <h1> @Model.Name</h1>
            <h2>@Model.Description</h2>
            <div class="imgFocusWinner">
                <img cla src="../img/personagens/@(Model.Name)W.jpg" />
            </div>



            <div class="bottomBar">
                <div class="alignCel">
                    <h4>L</h4>
                    <p>@Model.Fights</p>
                </div>
                <div class="alignCel">
                    <h4>V</h4>
                    <p>@Model.Victories</p>
                </div>
                <div class="alignCel">
                    <h4>D</h4>
                    <p>@Model.Defeats</p>
                </div>
                <div class="alignCel">
                    <h4>AM</h4>
                    <p>@Model.MartialArts</p>
                </div>
            </div>
        </div>
        <footer id="suporte">
            <h1>@Model.Age</h1>
        </footer>
    </span>


</div>

Duozin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/sass/style.css" asp-append-version="true" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
</head>

<body>
    <aside class="menuLateral">

        <li>
            <a asp-area="" asp-controller="Duozin" asp-action="Index">

                <i class='bx bxs-home'></i>
                <p>Home</p>
            </a>
        </li>


        <li>
            <a asp-area="" asp-controller="Duozin" asp-action="Personagens">
                <i class='bx bxs-grid'></i>

                <p>Duozin?</p>
            </a>
        </li>


        <li>
            <a asp-area="" asp-controller="Duozin" asp-action="List">
                <i class='bx bx-list-ul'></i>
                <p>Personagens</p>
            </a>
        </li>
    </aside>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/index.js"></script>
    <script src="~/lib/bootstrap/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>